---
title: "HTS Models"
author: "Meghna Diwan"
date: "5/29/2020"
output: html_document
---

```{r}
library(data.table)
library(tidyverse)
library(lubridate)
library(xts)
library(leaflet)
library(ggfortify)
library(tidyquant)
library(forecast)
library(tseries)
library(TSA)
library(hts)
library(fpp2)
library(tsbox)
rm(list = ls())
gc()
```

# Import Data
```{r}
datapath = "/Volumes/SSD/TS-Project/data"

# City, Type, Family
train <- fread(file=paste(datapath,"subset/train_city_type_item.csv",sep="/"))
test <- fread(file=paste(datapath,"subset/test_city_type_item.csv",sep="/"))
```

# Plots for TS and Dates
```{r}
train %>%
  mutate(date =  as.Date(date, "%Y-%m-%d")) %>%
  group_by(date) %>%
  summarise(sales = sum(tot_sales)) %>%
  ggplot(aes(date, sales)) +
  geom_line(color = "blue")

train %>%
  mutate(wday = wday(date, label = TRUE),
         month = month(date, label = TRUE)) %>%
  mutate(wday = fct_relevel(wday, c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))) %>%
  group_by(wday, month) %>%
  summarise(mean_sales = mean(tot_sales)) %>%
  ggplot(aes(month, wday, fill = mean_sales)) +
  geom_tile() +
  labs(x = "Month of the year", y = "Day of the week") +
  scale_fill_distiller(palette = "Spectral")
```

# Plot by Type
```{r}
train %>%
  mutate(date =  as.Date(date, "%Y-%m-%d")) %>%
  group_by(date, type) %>%
  summarise(sales = sum(tot_sales)) %>%
  filter(sales > 600) %>%
  ggplot(aes(date, sales, color = type)) +
  geom_line()
```

# Plot Oil price
```{r}
train %>%
  mutate(date =  as.Date(date, "%Y-%m-%d")) %>%
  group_by(date) %>%
  summarise(sales = sum(tot_sales), price = mean(price)) %>%
  mutate(oilprice = ( min(sales, na.rm = TRUE) + (price-min(price, na.rm=TRUE)) / (max(price, na.rm = TRUE) - min(price, na.rm = TRUE)) * (max(sales, na.rm = TRUE) - min(sales, na.rm = TRUE)) )) %>%
  ggplot(aes(date, sales)) +
  geom_line() +
  geom_line(aes(date, oilprice), color = "blue") +
  ggtitle("Total sales (black) with oilprice (blue)")
```


# Plot of Perishables
```{r}
train %>%
  ggplot(aes(family, fill = perishable)) +
  geom_bar(position = "fill") +
  coord_flip() +
  labs(y = "Total perishable proportion", x = "")
```


# Transform to Wide form
```{r}
train_wide = spread(train, hts_label, tot_sales)
train_wide[is.na(train_wide)] = 0
train_wide = train_wide %>%
                  select(-city, -type, -family, -price, -n_promotion, -perishable, -national_flag,
                         -holiday_flag, -pay.day_flag, -V1) %>%
                  group_by(date) %>%
                  summarise_all(funs(sum))
train.ts = ts(train_wide[2:ncol(train_wide)], frequency=365.25, 
     start = c(year("2013-01-01"), 1))
```

```{r}
unique(test$date)
```

# Run HTS
```{r}
train.hts = hts(train.ts, characters = c(2, 1, 5))
summary(train.hts)
smatrix(train.hts)
```

# Plot HTS
```{r}
# aggts1 <- aggts(train.hts, levels = 1) # City Level
# aggts2 <- aggts(train.hts, levels = c(0, 2)) # Type Level
# aggts3 <- aggts(train.hts, levels = c(0, 3)) # Item Family Level
# 
# # Graph by City
# train.hts %>% aggts(levels=0:1) %>%
#   autoplot(facet=TRUE) +
#   xlab("Year") + ylab("Total Sales") + ggtitle("Grocery Sales by City")
# 
# # Graph by Type
# train.hts %>% aggts(levels=0:2) %>%
#   autoplot(facet=TRUE) +
#   xlab("Year") + ylab("Total Sales") + ggtitle("Grocery Sales by City & Type")
# 
# # Graph by Item Family
# # Graph by Store and Item Family
# fcsts <- aggts(comb, levels=0:3)
# groups <- aggts(data.hts, levels=0:3)
# autoplot(fcsts) + autolayer(groups)
```

# Train - Val Split
```{r}
data.hts = window(train.hts, start = 2013, end = 2017.541) # 1659 dates
summary(data.hts)
val.hts = window(train.hts, start = 2017.542) # 20 dates
summary(val.hts)
```

# Visualization of the train-test split
```{r}
train_dt <- train %>%
  distinct(date) %>%
  head(-20) %>%
  mutate(dset = "train")

val_dt <- train %>%
  distinct(date) %>%
  tail(20) %>%
  mutate(dset = "validation")

test_dt <- test %>%
  distinct(date) %>%
  mutate(dset = "test")

train_dt <- train_dt %>%
  bind_rows(val_dt) %>%
  bind_rows(test_dt) %>%
  mutate(year = year(date))

train_dt$date = ymd(as.Date(train_dt$date, "%Y-%m-%d"))
year(train_dt$date) = 2017

train_dt %>%
  filter(!is.na(date)) %>%
  ggplot(aes(date, year, color = dset)) +
  geom_point(shape = "|", size = 10) +
  scale_x_date(date_labels = "%B", date_breaks = "1 month") +
  scale_y_reverse() +
  theme(legend.position = "bottom", axis.text.x  = element_text(angle=45, hjust=1, vjust=0.9)) +
  labs(color = "Data set") +
  guides(color = guide_legend(override.aes = list(size = 4, pch = 15)))
```

# SMAPE
```{r}
smape = function(y_pred, y_actual) {
  error = mean(abs(y_pred - y_actual)/(abs(y_actual) + abs(y_pred)))
  return(error)
}
```

# Base Model
```{r}
rw.top.down = forecast(
  data.hts, h = 20, method = "tdfp", fmethod = "rw",
  keep.fitted = TRUE, keep.resid = TRUE
)

rw.bottom.up = forecast(
  data.hts, h = 20, method = "bu", fmethod = "rw",
  keep.fitted = TRUE, keep.resid = TRUE
)

rw.middle.out = forecast(
  data.hts, h = 20, method = "mo", fmethod = "rw", level = 2,
  keep.fitted = TRUE, keep.resid = TRUE
)

rw.comb = forecast(
  data.hts, h = 20, method = "comb", fmethod = "rw",
  keep.fitted = TRUE, keep.resid = TRUE
)


# Forecasting Benchmarks

# - meanf: simply take the mean
#- naive: use last value
#- snaive: seasonal naive, take the value of the last same season
#- rwf: random walk forecast, use drift

# data.hts %>% meanf(h=20) %>% autoplot
# goog %>% naive(h=20) %>% autoplot
# data.hts %>% snaive(h=20) %>% autoplot
# goog %>% rwf(drift=TRUE, h=50) %>% autoplot


base_results = rbind(smape(rw.top.down$bts, val.hts$bts),
                smape(rw.bottom.up$bts, val.hts$bts),
                smape(rw.middle.out$bts, val.hts$bts),
                smape(rw.comb$bts, val.hts$bts))
rownames(base_results) = c("top.down",  "bottom.up",  "middle.out", "combination")
base_results

```


# Forecast
```{r}
top.down = forecast(
  data.hts, h = 20, method = "tdfp", fmethod = "arima",
  keep.fitted = TRUE, keep.resid = TRUE
)

bottom.up = forecast(
  data.hts, h = 20, method = "bu", fmethod = "arima",
  keep.fitted = TRUE, keep.resid = TRUE
)

middle.out = forecast(
  data.hts, h = 20, method = "mo", fmethod = "arima", level = 2,
  keep.fitted = TRUE, keep.resid = TRUE
)

comb = forecast(
  data.hts, h = 20, method = "comb", fmethod = "arima",
  keep.fitted = TRUE, keep.resid = TRUE
)

comb_wls = forecast(
  data.hts, h = 20, method = "comb", fmethod = "arima", weights = "wls",
  keep.fitted = TRUE, keep.resid = TRUE
)
 
comb_wls_alg = forecast(
  data.hts, h = 20, method = "comb", fmethod = "arima", weights = "wls", algorithms = "lu",
  keep.fitted = TRUE, keep.resid = TRUE
)

comb_nseries = forecast(
  data.hts, h = 20, method = "comb", fmethod = "arima", weights = "nseries",
  keep.fitted = TRUE, keep.resid = TRUE
)

```

## SMAPE Errors
```{r}
results = rbind(smape(top.down$bts, val.hts$bts),
                smape(bottom.up$bts, val.hts$bts),
                smape(middle.out$bts, val.hts$bts),
                smape(comb$bts, val.hts$bts),
                smape(comb_wls$bts, val.hts$bts),
                smape(comb_wls_alg$bts, val.hts$bts), 
                smape(comb_nseries$bts, val.hts$bts))
rownames(results) = c("top.down",  "bottom.up",  "middle.out", 
                      "combination", "comb_wls", "comb_wls_alg", "comb_nseries")
results
```

## CV
```{r}
hts.CV = function(y, window, h) {
  cv.error = matrix(ncol = 1)
  
  for (i in seq(1, nrow(y) - (window + h) + 1)) {
    train_start = i
    train_end = i + window - 1
    test_start = i + window
    test_end = i + window + h - 1
    #print("/n")
    #cat(train_start, train_end, test_start, test_end, sep = " ")
    train_y = subset(y, start = train_start, end = train_end)
    #print(nrow(train_y))
    test_y = subset(y, start = test_start, end = test_end)
    #print(nrow(test_y))
    
    train_hts = hts(train_y, characters = c(2, 1, 5))
    test_hts = hts(test_y, characters = c(2, 1, 5))
    
    fc = forecast(train_hts, h = h, method = "comb", fmethod = "arima", weights = "wls",
    keep.fitted = TRUE, keep.resid = TRUE)
    print(paste("Done", as.character(i)))
    acc = smape(fc$bts, test_hts$bts)
    cv.error = rbind(cv.error, acc)
  }
  
  return(cv.error)
}
```


```{r}
start.time <- Sys.time()
cv.acc = hts.CV(y = train.ts, window = 1640, h = 30) # takes 11 mins to run one cv
end.time <- Sys.time()
(time.taken <- end.time - start.time)
```

```{r}
mean(cv.acc, na.rm = T)
sd(cv.acc, na.rm = T)
```
