---
title: "HTS"
author: "Aarti Rao"
date: "5/28/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=14, echo=TRUE, warning=FALSE, message=FALSE, fig.keep = 'all')
```

```{r}
library(data.table)
library(tidyverse)
library(lubridate)
library(xts)
library(leaflet)
library(ggfortify)
library(tidyquant)
library(forecast)
library(tseries)
library(TSA)
library(hts)
library(fpp2)
library(tsbox)
```


# Create HTS TS
```{r}
datapath = "C:/Users/aarti/Downloads"
train = fread(file=paste(datapath,"train_store_fam.csv",sep="/"))
subset = train %>% 
  select(date, store_char, cluster_nbr, family_nbr, tot_sales) %>%
  mutate(date = as.Date(date, format = "%Y-%m-%d")) %>%
  filter(date >= as.Date('2013-01-01') & date < as.Date('2014-01-01'))
  
# family and cluster
subset$id = paste0(subset$cluster_nbr,subset$family_nbr)
subset_wide = spread(subset, id, tot_sales)
subset_wide[is.na(subset_wide)] = 0
subset_wide = subset_wide %>%
                  select(-store_char, -cluster_nbr, -family_nbr) %>%
                  group_by(date) %>%
                  summarise_all(funs(sum))
subset.ts = ts(subset_wide[,2:365]) 
# Find nodes for each level
n_nodes = subset %>%
            group_by(cluster_nbr) %>%
            summarise(n_fam = COUNT_UNIQUE(family_nbr))
# Create HTS
subset_hts = hts(subset.ts, characters = c(3, 5))
#subset_hts = hts(subset.ts[1:364], nodes=list(17, c(n_nodes$n_fam)))
# Graph by stores
subset_hts %>% aggts(levels=0:1) %>%
  autoplot(facet=TRUE) +
  xlab("time") + ylab("Sales") + ggtitle("Grocery Stores")
```