---
title: "Create Train & Test"
author: "Meghna Diwan"
date: "5/21/2020"
output: html_document
---

```{r}
library(data.table)
library(tidyverse)
library(lubridate)
library(xts)
library(leaflet)
library(ggfortify)
library(tidyquant)

library(forecast)
library(tseries)
library(TSA)
rm(list = ls())
gc()
```

# Import Data
```{r}
datapath = "/Volumes/SSD/TS-Project/data"
dtrain <- fread(file=paste(datapath,"full/train.csv",sep="/"))
stores <- fread(file=paste(datapath,"full/stores.csv",sep="/"))
oil <- fread(file=paste(datapath,"full/oil_new.csv",sep="/"))
items <- fread(file=paste(datapath,"full/items.csv",sep="/"))
transactions <- fread(file = paste(datapath, 'full/transactions.csv', sep = "/"))
holiday = fread(file = paste(datapath, 'full/holidays_new.csv', sep = "/"))
test = fread(file = paste(datapath, 'full/test.csv', sep = "/"))
```

# Check Missing Data
```{r}
data.frame(dtrain = colSums(is.na(train)))
data.frame(stores = colSums(is.na(stores)))
data.frame(oil = colSums(is.na(oil)))
data.frame(items = colSums(is.na(items)))
data.frame(transactions = colSums(is.na(transactions)))
data.frame(holiday = colSums(is.na(holiday)))
data.frame(test = colSums(is.na(test)))
```

# Make promotions binary
```{r}
# Train
dtrain$promotion = ifelse(dtrain$onpromotion == TRUE, 1, 0)
dtrain$promotion[is.na(dtrain$promotion)] = 0

# Test
test$promotion = ifelse(test$onpromotion == TRUE, 1, 0)
test$promotion[is.na(test$promotion)] = 0
```

# Collapse to item level
```{r}
# Train
train_item <- left_join(dtrain, items)
train_item_lvl = train_item %>%
                    select(date, item_nbr, family, unit_sales, promotion, perishable) %>%
                    group_by(date, family) %>%
                    summarize(tot_sales = sum(unit_sales), 
                              n_promotion = sum(promotion),
                              perishable = max(perishable))

# Test
test_item <- left_join(test, items)
test_item_lvl = test_item %>%
                    select(date, item_nbr, family, promotion, perishable) %>%
                    group_by(date, family) %>%
                    summarize(n_promotion = sum(promotion),
                              perishable = max(perishable))

```

# Write to CSV
```{r}
write.csv(train_item_lvl,'/Volumes/SSD/TS-Project/data/subset/train_item.csv')
write.csv(test_item_lvl,'/Volumes/SSD/TS-Project/data/subset/test_item.csv')
```


## Create Date-Store-Family Level
```{r}
library(readxl)
item_map = read_excel(path = paste(datapath,"full/store_item_map.xlsx",sep="/"), sheet = "item_map")
store_map = read_excel(path = paste(datapath,"full/store_item_map.xlsx",sep="/"), sheet = "store_map")
cluster_map = read_excel(path = paste(datapath,"full/store_item_map.xlsx",sep="/"), 
                         sheet = "cluster_map")
# Add maps
items = left_join(items, item_map, by= 'family')
stores = left_join(stores, store_map, by = 'store_nbr')
stores = left_join(stores, cluster_map, by = 'cluster')

## TRAIN
train_item <- left_join(dtrain, items, by="item_nbr")
train_fam = train_item %>%
              select(date, store_nbr, item_nbr, family, family_nbr, 
                     unit_sales, promotion, perishable) %>%
              group_by(date, store_nbr, family, family_nbr) %>%
              summarize(tot_sales = sum(unit_sales),
                        n_promotion = sum(promotion),
                        perishable = max(perishable))
train_fam = left_join(train_fam, stores, by = "store_nbr")
write.csv(train_fam, paste(datapath, "subset/train_store_fam.csv", sep = "/"))


## TEST
test_item <- left_join(test, items, by="item_nbr")
test_fam = test_item %>%
              select(date, store_nbr, item_nbr, family, family_nbr, promotion, perishable) %>%
              group_by(date, store_nbr, family, family_nbr) %>%
              summarize(n_promotion = sum(promotion),
                        perishable = max(perishable))
test_fam = left_join(test_fam, stores, by = "store_nbr")
write.csv(test_fam, paste(datapath, "subset/test_store_fam.csv", sep = "/"))
```

## Create City, Type, Top 5 Items Level
```{r}
# Train
train = fread(file=paste(datapath,"subset/train_store_fam.csv",sep="/"))

## Find Top 5 items per category
train_top_items = train %>%
            filter(city %in% c("Quito", "Guayaquil")) %>%
            group_by(city, type, family) %>%
            summarize(tot_sales = sum(tot_sales)) %>%
            arrange(city, type, desc(tot_sales)) %>%
            top_n(5, tot_sales)

## Keep on those combinations identified
train_subset = inner_join(train_top_items, train, by= c("city", "type", "family"))

# Collapse to Date, City, Type and Item Level
train_subset_summ = train_subset %>%
                select(date, city, type, family, family_nbr, tot_sales.y, n_promotion, n_perishable) %>%
                group_by(date, city, type, family, family_nbr) %>%
                summarise(tot_sales = sum(tot_sales.y),
                          n_promotion = sum(n_promotion),
                          perishable = sum(n_perishable))

# Create label for HTS
train_subset_summ$city_label = substr(train_subset_summ$city, 1, 2)
train_subset_summ$hts_label = paste0(train_subset_summ$city_label,train_subset_summ$type,
                                 train_subset_summ$family_nbr)

# Add Oil and Holidays
train_subset_summ = left_join(train_subset_summ, oil, by="date")
train_subset_summ = left_join(train_subset_summ, holiday, by="date")

# Add Flag if Date is pay day (15 or end of the month)
train_subset_summ$date = as.Date(train_subset_summ$date, "%Y-%m-%d")
train_subset_summ$day = day(train_subset_summ$date)
train_subset_summ$pay.day_flag = ifelse(train_subset_summ$day %in% c(15, 28, 29, 30, 31), 1, 0)

# Save
train_subset_summ = train_subset_summ %>% 
  select(date, city, type, family, hts_label, price, n_promotion, perishable, 
         national_flag, holiday_flag, pay.day_flag, tot_sales)

write.csv(train_subset_summ, paste(datapath, "subset/train_city_type_item.csv", sep = "/"))
```


```{r}
# Test
test = fread(file=paste(datapath,"subset/test_store_fam.csv",sep="/"))

## Keep on those combinations identified in train
test_subset = inner_join(train_top_items, test, by= c("city", "type", "family"))

# Collapse to Date, City, Type and Item Level
test_subset_summ = test_subset %>%
                select(date, city, type, family, family_nbr, n_promotion, perishable) %>%
                group_by(date, city, type, family, family_nbr) %>%
                summarise(n_promotion = sum(n_promotion),
                          perishable = max(perishable))

# Create label for HTS
test_subset_summ$city_label = substr(test_subset_summ$city, 1, 2)
test_subset_summ$hts_label = paste0(test_subset_summ$city_label,test_subset_summ$type,
                                 test_subset_summ$family_nbr)

# Add Oil and Holidays
test_subset_summ = left_join(test_subset_summ, oil, by="date")
test_subset_summ = left_join(test_subset_summ, holiday, by="date")

# Add Flag if Date is pay day (15 or end of the month)
test_subset_summ$date = as.Date(test_subset_summ$date, "%Y-%m-%d")
test_subset_summ$day = day(test_subset_summ$date)
test_subset_summ$pay.day_flag = ifelse(test_subset_summ$day %in% c(15, 28, 29, 30, 31), 1, 0)

# Save
test_subset_summ = test_subset_summ %>% 
  select(date, city, type, family, hts_label, price, n_promotion, perishable, 
         national_flag, holiday_flag, pay.day_flag)

write.csv(test_subset_summ, paste(datapath, "subset/test_city_type_item.csv", sep = "/"))

```


## Create City, Store, Top 5 Items Level
```{r}
# Train
train = fread(file=paste(datapath,"subset/train_store_fam.csv",sep="/"))

## Find Top 5 items per category
train_top_items = train %>%
            filter(city %in% c("Quito", "Guayaquil")) %>%
            group_by(city, store_nbr, family) %>%
            summarize(tot_sales = sum(tot_sales)) %>%
            arrange(city, store_nbr, desc(tot_sales)) %>%
            top_n(5, tot_sales)

## Keep on those combinations identified
train_subset = inner_join(train_top_items, train, by= c("city", "store_nbr", "family"))

# Collapse to Date, City, Type and Item Level
train_subset_summ = train_subset %>%
                select(date, city, store_nbr, store_char, family, family_nbr, 
                       tot_sales.y, n_promotion, perishable) %>%
                group_by(date, city, store_nbr, store_char, family, family_nbr) %>%
                summarise(tot_sales = sum(tot_sales.y),
                          n_promotion = sum(n_promotion),
                          perishable = max(perishable))

# Create label for HTS
train_subset_summ$city_label = substr(train_subset_summ$city, 1, 2)
train_subset_summ$hts_label = paste0(train_subset_summ$city_label,train_subset_summ$store_char,
                                 train_subset_summ$family_nbr)

# Add Oil and Holidays
train_subset_summ = left_join(train_subset_summ, oil, by="date")
train_subset_summ = left_join(train_subset_summ, holiday, by="date")

# Add Flag if Date is pay day (15 or end of the month)
train_subset_summ$date = as.Date(train_subset_summ$date, "%Y-%m-%d")
train_subset_summ$day = day(train_subset_summ$date)
train_subset_summ$pay.day_flag = ifelse(train_subset_summ$day %in% c(15, 28, 29, 30, 31), 1, 0)

# Save
train_subset_summ = train_subset_summ %>% ungroup() %>%
  select(date, city, store_nbr, family, hts_label, price, n_promotion, perishable, 
         national_flag, holiday_flag, pay.day_flag, tot_sales)

write.csv(train_subset_summ, paste(datapath, "subset/train_city_store_item.csv", sep = "/"))
```


```{r}
# Test
test = fread(file=paste(datapath,"subset/test_store_fam.csv",sep="/"))

## Keep on those combinations identified in train
test_subset = inner_join(train_top_items, test, by= c("city", "store_nbr", "family"))

# Collapse to Date, City, Type and Item Level
test_subset_summ = test_subset %>%
                select(date, city, store_nbr, store_char, family, family_nbr, 
                       n_promotion, perishable) %>%
                group_by(date, city, store_nbr, store_char, family, family_nbr) %>%
                summarise(n_promotion = sum(n_promotion),
                          perishable = max(perishable))

# Create label for HTS
test_subset_summ$city_label = substr(test_subset_summ$city, 1, 2)
test_subset_summ$hts_label = paste0(test_subset_summ$city_label,test_subset_summ$store_char,
                                 test_subset_summ$family_nbr)

# Add Oil and Holidays
test_subset_summ = left_join(test_subset_summ, oil, by="date")
test_subset_summ = left_join(test_subset_summ, holiday, by="date")

# Add Flag if Date is pay day (15 or end of the month)
test_subset_summ$date = as.Date(test_subset_summ$date, "%Y-%m-%d")
test_subset_summ$day = day(test_subset_summ$date)
test_subset_summ$pay.day_flag = ifelse(test_subset_summ$day %in% c(15, 28, 29, 30, 31), 1, 0)

# Save
test_subset_summ = test_subset_summ %>% ungroup() %>%
  select(date, city, store_nbr, family, hts_label, price, n_promotion, perishable, 
         national_flag, holiday_flag, pay.day_flag)

write.csv(test_subset_summ, paste(datapath, "subset/test_city_store_item.csv", sep = "/"))
```
